###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:
#################-POSTGRES-##########################
   postgres:
    container_name: postgres
    image: docker.io/bitnami/postgresql:11
    restart: always
    volumes:
         - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - db.env
    ports:
        - "5432:5432"
    environment:
        - POSTGRESQL_USER=postgres
        - POSTGRESQL_DATABASE=tarea1
        - POSTGRESQL_PASSWORD=postgres

###################-SERVIDOR-#########################   
   servidor:
    container_name: servidor
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app/backend
    ports:
        - "3000:3000"
    depends_on:
        - postgres


###################-CLIENTE-#########################   
   cliente:
     container_name: cliente
     build: ./Frontend
     restart: always
     ports:
         - "5000:80"
     depends_on:
         - postgres
         - servidor

