###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:
#################-POSTGRES-##########################
   postgres:
    container_name: postgres
    image: docker.io/bitnami/postgresql:11
    restart: always
    env_file:
        - db.env
    volumes:
    # Aquí se monta el volumen de la carpeta del proyecto orientado a la topología
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5433:5432"
    
###################-SERVIDOR-#########################   
   servidor:
    container_name: servidor
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app/backend
    ports:
        - "3000:3000"
    depends_on:
        - postgres


###################-CLIENTE-#########################   
   cliente:
     container_name: cliente
     build: ./Frontend
     restart: always
     ports:
         - "5000:80"
     depends_on:
         - postgres
         - servidor

